name: DockerHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_PATH: nstwf/deployer

    strategy:
      matrix:
        deployer_version: ['6.8.0', '7.3.1', '7.3.3', '7.4.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Create a new builder instance
        run: |
          docker buildx create --use

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_BUILD_TOKEN }}

      - name: Build and push Docker images (multi-platform)
        run: |
          docker buildx build \
            --build-arg DEPLOYER_VERSION=${{ matrix.deployer_version }} \
            -t ${{ env.DOCKER_IMAGE_PATH }}:${{ matrix.deployer_version }} \
            --push .