name: DockerHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_PATH: nstwf/deployer

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    strategy:
      matrix:
        deployer_version: ['6.8.0', '7.3.1', '7.3.3', '7.4.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        run: echo ${{ secrets.DOCKER_BUILD_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker images
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_PATH }}:${{ matrix.deployer_version }} --build-arg DEPLOYER_VERSION=${{ matrix.deployer_version }} .
          docker push ${{ env.DOCKER_IMAGE_PATH }}:${{ matrix.deployer_version }}
