name: Build and Push Using Shared Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push:
    if: github.event_name != 'pull_request'

    strategy:
      matrix:
        include:
          - php-version: "8.0"
            deployer-version: "6.9.0"
          - php-version: "8.0"
            deployer-version: "7.5.12"

    uses: nstwf-docker/docker-ci/.github/workflows/docker-build-push.yaml@main
    secrets: inherit
    with:
      image_version: ${{ matrix.deployer-version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
      ghcr_image: ghcr.io/${{ github.repository }}
      docker_extra_build_args: |
        PHP_VERSION=${{ matrix.php-version }}
        DEPLOYER_VERSION=${{ matrix.deployer-version }}

  build-push-pr:
    if: github.event_name == 'pull_request'

    strategy:
      matrix:
        include:
          - php-version: "8.0"
            deployer-version: "6.9.0"
          - php-version: "8.0"
            deployer-version: "7.5.12"

    uses: nstwf-docker/docker-ci/.github/workflows/docker-build-push-pr.yaml@main
    secrets: inherit
    with:
      image_version: ${{ matrix.deployer_version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
      docker_extra_build_args: |
        PHP_VERSION=${{ matrix.php-version }}
        DEPLOYER_VERSION=${{ matrix.deployer-version }}
